// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a cold call script based on business and customer information.
 *
 * - generateColdCallScript - A function that generates a cold call script.
 * - GenerateColdCallScriptInput - The input type for the generateColdCallScript function.
 * - GenerateColdCallScriptOutput - The return type for the generateColdCallScript function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateColdCallScriptInputSchema = z.object({
  businessInfo: z.string().describe('Information about the user\s business and sales goals.'),
  customerInfo: z.string().describe('Information about the target customer, either a URL or a text summary.'),
});
export type GenerateColdCallScriptInput = z.infer<typeof GenerateColdCallScriptInputSchema>;

const GenerateColdCallScriptOutputSchema = z.object({
  script: z.string().describe('The generated cold call script.'),
});
export type GenerateColdCallScriptOutput = z.infer<typeof GenerateColdCallScriptOutputSchema>;

export async function generateColdCallScript(input: GenerateColdCallScriptInput): Promise<GenerateColdCallScriptOutput> {
  return generateColdCallScriptFlow(input);
}

const generateColdCallScriptPrompt = ai.definePrompt({
  name: 'generateColdCallScriptPrompt',
  input: {schema: GenerateColdCallScriptInputSchema},
  output: {schema: GenerateColdCallScriptOutputSchema},
  prompt: `You are a sales expert. Generate a cold call script based on the following information. The script should be concise and engaging.

Business Information: {{{businessInfo}}}

Customer Information: {{{customerInfo}}}

Script:`, 
});

const generateColdCallScriptFlow = ai.defineFlow(
  {
    name: 'generateColdCallScriptFlow',
    inputSchema: GenerateColdCallScriptInputSchema,
    outputSchema: GenerateColdCallScriptOutputSchema,
  },
  async input => {
    const {output} = await generateColdCallScriptPrompt(input);
    return output!;
  }
);
